version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: gamebox-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: gamebox
      POSTGRES_USER: gamebox
      POSTGRES_PASSWORD: gamebox

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
